#if !canImport(ObjectiveC)
import XCTest

extension AdhanTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AdhanTests = [
        ("testCalculationMethods", testCalculationMethods),
        ("testCurrentPrayer", testCurrentPrayer),
        ("testDiyanet", testDiyanet),
        ("testEgyptian", testEgyptian),
        ("testExtremeLocation", testExtremeLocation),
        ("testHighLatitudeRule", testHighLatitudeRule),
        ("testInvalidDate", testInvalidDate),
        ("testInvalidLocation", testInvalidLocation),
        ("testMoonsightingMethod", testMoonsightingMethod),
        ("testMoonsightingMethodHighLat", testMoonsightingMethodHighLat),
        ("testNextPrayer", testNextPrayer),
        ("testNightPortion", testNightPortion),
        ("testOffsets", testOffsets),
        ("testPrayerTimes", testPrayerTimes),
        ("testTehranMethod", testTehranMethod),
        ("testTimeForPrayer", testTimeForPrayer),
    ]
}

extension AstronomicalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AstronomicalTests = [
        ("testAltitudeOfCelestialBody", testAltitudeOfCelestialBody),
        ("testAngleInterpolation", testAngleInterpolation),
        ("testCalendricalDate", testCalendricalDate),
        ("testDaysSinceSolstice", testDaysSinceSolstice),
        ("testInterpolation", testInterpolation),
        ("testJulianDay", testJulianDay),
        ("testJulianHours", testJulianHours),
        ("testLeapYear", testLeapYear),
        ("testRightAscensionEdgeCase", testRightAscensionEdgeCase),
        ("testSolarCoordinates", testSolarCoordinates),
        ("testSolarTime", testSolarTime),
        ("testTransitAndHourAngle", testTransitAndHourAngle),
    ]
}

extension MathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MathTests = [
        ("testAngleConversion", testAngleConversion),
        ("testClosestAngle", testClosestAngle),
        ("testMinuteRounding", testMinuteRounding),
        ("testNormalizing", testNormalizing),
        ("testTimeComponents", testTimeComponents),
    ]
}

extension QiblaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QiblaTests = [
        ("testAsia", testAsia),
        ("testEurope", testEurope),
        ("testNorthAmerica", testNorthAmerica),
        ("testSouthPacific", testSouthPacific),
    ]
}

extension SunnahTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SunnahTests = [
        ("testSunnahTimesDST1", testSunnahTimesDST1),
        ("testSunnahTimesDST2", testSunnahTimesDST2),
        ("testSunnahTimesLondon", testSunnahTimesLondon),
        ("testSunnahTimesNY", testSunnahTimesNY),
        ("testSunnahTimesOslo", testSunnahTimesOslo),
    ]
}

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testTimes", testTimes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AdhanTests.__allTests__AdhanTests),
        testCase(AstronomicalTests.__allTests__AstronomicalTests),
        testCase(MathTests.__allTests__MathTests),
        testCase(QiblaTests.__allTests__QiblaTests),
        testCase(SunnahTests.__allTests__SunnahTests),
        testCase(TimeTests.__allTests__TimeTests),
    ]
}
#endif
