fastlane_version "2.163.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    test(scheme: "Adhan-macOS", swift_version: "4.0")
    test(scheme: "Adhan-macOS", swift_version: "5.3")

    test(scheme: "Adhan-tvOS", swift_version: "4.0")
    test(scheme: "Adhan-tvOS", swift_version: "5.3")

    test(scheme: "Adhan-iOS", swift_version: "4.0")
    test(scheme: "Adhan-iOS", swift_version: "5.3")
  end

  lane :test do |options|
    _test(options) rescue _test(options)
  end

private_lane :_test do |options|
    # Completely skips package caching for the build phase
    skip_spm = "-disablePackageRepositoryCache"

    if options[:scheme].include? "macOS"
        scan(scheme: options[:scheme], clean: true, code_coverage: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]} MACOSX_DEPLOYMENT_TARGET=10.13 #{skip_spm}", destination: "platform=macOS")
    elsif options[:scheme].include? "tvOS"
        scan(scheme: options[:scheme], clean: true, code_coverage: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]} #{skip_spm}", destination: "platform=tvOS Simulator,name=Apple TV")
    else
        scan(scheme: options[:scheme], clean: true, code_coverage: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]} #{skip_spm}", destination: "platform=iOS Simulator,name=iPhone 16 Pro")
    end
  end

  lane :test_ci do
    test(scheme: "Adhan-macOS", swift_version: ENV["SWIFT_VERSION"])
    test(scheme: "Adhan-tvOS", swift_version: ENV["SWIFT_VERSION"])
    test(scheme: "Adhan-iOS", swift_version: ENV["SWIFT_VERSION"])
  end
end
