# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.32.1"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    test(scheme: "Adhan", swift_version: "5.0")
    test(scheme: "Adhan-macOS", swift_version: "5.0")
    test(scheme: "Adhan-tvOS", swift_version: "5.0")

    test(scheme: "Adhan", swift_version: "4.2")
    test(scheme: "Adhan-macOS", swift_version: "4.2")
    test(scheme: "Adhan-tvOS", swift_version: "4.2")

    test(scheme: "Adhan", swift_version: "4.0")
    test(scheme: "Adhan-macOS", swift_version: "4.0")
    test(scheme: "Adhan-tvOS", swift_version: "4.0")
  end

  lane :test do |options|
    # Sometimes Travis CI would fail due to timeout. 
    # Not sure why but just rerunning the test perfectly fixes it. :[
    # Maybe it is related to some racing when running in CI, but it never reproducible in a local env.
    _test(options) rescue _test(options)
  end

  private_lane :_test do |options|
    if options[:scheme].include? "macOS"
        scan(scheme: options[:scheme], clean: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]}", destination: "platform=macOS")
    else
        scan(scheme: options[:scheme], clean: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]}")
    end
  end

  lane :test_ci do
    test(scheme: ENV["SCHEME"], swift_version: ENV["SWIFT_VERSION"])
  end
end