fastlane_version "2.163.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    test(scheme: "Adhan-macOS", swift_version: "4.0")
    test(scheme: "Adhan-macOS", swift_version: "5.3")

    test(scheme: "Adhan-tvOS", swift_version: "4.0")
    test(scheme: "Adhan-tvOS", swift_version: "5.3")

    test(scheme: "Adhan-iOS", swift_version: "4.0")
    test(scheme: "Adhan-iOS", swift_version: "5.3")
  end

  lane :test do |options|
    _test(options) rescue _test(options)
  end

  private_lane :_test do |options|
    if options[:scheme].include? "macOS"
        scan(scheme: options[:scheme], clean: true, code_coverage: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]}", destination: "platform=macOS")
    else
        scan(scheme: options[:scheme], clean: true, code_coverage: true, xcargs: "SWIFT_VERSION=#{options[:swift_version]}")
    end
  end

  lane :test_ci do
    test(scheme: "Adhan-macOS", swift_version: ENV["SWIFT_VERSION"])
    test(scheme: "Adhan-tvOS", swift_version: ENV["SWIFT_VERSION"])
    test(scheme: "Adhan-iOS", swift_version: ENV["SWIFT_VERSION"])
  end
end
